#!/bin/sh
 #
 # 00screensaver-lock: lock workstation on hibernate or suspend

 username=radak # add username here; i.e.: username=foobar
 userhome=/home/$username
 export XAUTHORITY="$userhome/.Xauthority"
 export DISPLAY=":0"

  case "$1" in
    hibernate|suspend)
       su $username -c "/usr/bin/i3lock"
    ;;
    thaw|resume)
    ;;
    *) exit $NA
    ;;
 esac

